/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ILensInterface extends ethers.utils.Interface {
  functions: {
    "getDerivedPosition(uint256)": FunctionFragment;
    "getFeeAmounts(uint256,tuple,tuple)": FunctionFragment;
    "getPoolId(address,address)": FunctionFragment;
    "getPosition(uint256)": FunctionFragment;
    "getUnderlyingAmounts(tuple,tuple,bool)": FunctionFragment;
    "hub()": FunctionFragment;
    "isSettled(tuple,tuple)": FunctionFragment;
    "manager()": FunctionFragment;
    "quote(bytes,int256)": FunctionFragment;
    "quoteSingle(address,address,uint256,int256)": FunctionFragment;
    "simulate(bytes,int256)": FunctionFragment;
    "simulateSingle(address,address,uint256,int256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getDerivedPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeAmounts",
    values: [
      BigNumberish,
      {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolId",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnderlyingAmounts",
    values: [
      {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      boolean
    ]
  ): string;
  encodeFunctionData(functionFragment: "hub", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isSettled",
    values: [
      {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quote",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteSingle",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "simulate",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "simulateSingle",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getDerivedPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPoolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnderlyingAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSettled", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "simulate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "simulateSingle",
    data: BytesLike
  ): Result;

  events: {};
}

export class ILens extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ILensInterface;

  functions: {
    getDerivedPosition(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, number, number, number] & {
          owner: string;
          token0: string;
          token1: string;
          tierId: number;
          tickLower: number;
          tickUpper: number;
        },
        [BigNumber, BigNumber, BigNumber, number, number] & {
          liquidityD8: BigNumber;
          feeGrowthInside0Last: BigNumber;
          feeGrowthInside1Last: BigNumber;
          limitOrderType: number;
          settlementSnapshotId: number;
        },
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        info: [string, string, string, number, number, number] & {
          owner: string;
          token0: string;
          token1: string;
          tierId: number;
          tickLower: number;
          tickUpper: number;
        };
        position: [BigNumber, BigNumber, BigNumber, number, number] & {
          liquidityD8: BigNumber;
          feeGrowthInside0Last: BigNumber;
          feeGrowthInside1Last: BigNumber;
          limitOrderType: number;
          settlementSnapshotId: number;
        };
        settled: boolean;
        amount0: BigNumber;
        amount1: BigNumber;
        feeAmount0: BigNumber;
        feeAmount1: BigNumber;
      }
    >;

    getFeeAmounts(
      tokenId: BigNumberish,
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { feeAmount0: BigNumber; feeAmount1: BigNumber }
    >;

    getPoolId(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPosition(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, number, number, number] & {
          owner: string;
          token0: string;
          token1: string;
          tierId: number;
          tickLower: number;
          tickUpper: number;
        },
        [BigNumber, BigNumber, BigNumber, number, number] & {
          liquidityD8: BigNumber;
          feeGrowthInside0Last: BigNumber;
          feeGrowthInside1Last: BigNumber;
          limitOrderType: number;
          settlementSnapshotId: number;
        }
      ] & {
        info: [string, string, string, number, number, number] & {
          owner: string;
          token0: string;
          token1: string;
          tierId: number;
          tickLower: number;
          tickUpper: number;
        };
        position: [BigNumber, BigNumber, BigNumber, number, number] & {
          liquidityD8: BigNumber;
          feeGrowthInside0Last: BigNumber;
          feeGrowthInside1Last: BigNumber;
          limitOrderType: number;
          settlementSnapshotId: number;
        };
      }
    >;

    getUnderlyingAmounts(
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      settled: boolean,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amount0: BigNumber; amount1: BigNumber }
    >;

    hub(overrides?: CallOverrides): Promise<[string]>;

    isSettled(
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<[boolean] & { settled: boolean }>;

    manager(overrides?: CallOverrides): Promise<[string]>;

    quote(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        gasUsed: BigNumber;
      }
    >;

    quoteSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        gasUsed: BigNumber;
      }
    >;

    simulate(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        })[]
      ] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        hops: ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        })[];
      }
    >;

    simulateSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        }
      ] & {
        hop: [BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        };
      }
    >;
  };

  getDerivedPosition(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      [string, string, string, number, number, number] & {
        owner: string;
        token0: string;
        token1: string;
        tierId: number;
        tickLower: number;
        tickUpper: number;
      },
      [BigNumber, BigNumber, BigNumber, number, number] & {
        liquidityD8: BigNumber;
        feeGrowthInside0Last: BigNumber;
        feeGrowthInside1Last: BigNumber;
        limitOrderType: number;
        settlementSnapshotId: number;
      },
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      info: [string, string, string, number, number, number] & {
        owner: string;
        token0: string;
        token1: string;
        tierId: number;
        tickLower: number;
        tickUpper: number;
      };
      position: [BigNumber, BigNumber, BigNumber, number, number] & {
        liquidityD8: BigNumber;
        feeGrowthInside0Last: BigNumber;
        feeGrowthInside1Last: BigNumber;
        limitOrderType: number;
        settlementSnapshotId: number;
      };
      settled: boolean;
      amount0: BigNumber;
      amount1: BigNumber;
      feeAmount0: BigNumber;
      feeAmount1: BigNumber;
    }
  >;

  getFeeAmounts(
    tokenId: BigNumberish,
    info: {
      owner: string;
      token0: string;
      token1: string;
      tierId: BigNumberish;
      tickLower: BigNumberish;
      tickUpper: BigNumberish;
    },
    position: {
      liquidityD8: BigNumberish;
      feeGrowthInside0Last: BigNumberish;
      feeGrowthInside1Last: BigNumberish;
      limitOrderType: BigNumberish;
      settlementSnapshotId: BigNumberish;
    },
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { feeAmount0: BigNumber; feeAmount1: BigNumber }
  >;

  getPoolId(
    token0: string,
    token1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getPosition(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      [string, string, string, number, number, number] & {
        owner: string;
        token0: string;
        token1: string;
        tierId: number;
        tickLower: number;
        tickUpper: number;
      },
      [BigNumber, BigNumber, BigNumber, number, number] & {
        liquidityD8: BigNumber;
        feeGrowthInside0Last: BigNumber;
        feeGrowthInside1Last: BigNumber;
        limitOrderType: number;
        settlementSnapshotId: number;
      }
    ] & {
      info: [string, string, string, number, number, number] & {
        owner: string;
        token0: string;
        token1: string;
        tierId: number;
        tickLower: number;
        tickUpper: number;
      };
      position: [BigNumber, BigNumber, BigNumber, number, number] & {
        liquidityD8: BigNumber;
        feeGrowthInside0Last: BigNumber;
        feeGrowthInside1Last: BigNumber;
        limitOrderType: number;
        settlementSnapshotId: number;
      };
    }
  >;

  getUnderlyingAmounts(
    info: {
      owner: string;
      token0: string;
      token1: string;
      tierId: BigNumberish;
      tickLower: BigNumberish;
      tickUpper: BigNumberish;
    },
    position: {
      liquidityD8: BigNumberish;
      feeGrowthInside0Last: BigNumberish;
      feeGrowthInside1Last: BigNumberish;
      limitOrderType: BigNumberish;
      settlementSnapshotId: BigNumberish;
    },
    settled: boolean,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { amount0: BigNumber; amount1: BigNumber }
  >;

  hub(overrides?: CallOverrides): Promise<string>;

  isSettled(
    info: {
      owner: string;
      token0: string;
      token1: string;
      tierId: BigNumberish;
      tickLower: BigNumberish;
      tickUpper: BigNumberish;
    },
    position: {
      liquidityD8: BigNumberish;
      feeGrowthInside0Last: BigNumberish;
      feeGrowthInside1Last: BigNumberish;
      limitOrderType: BigNumberish;
      settlementSnapshotId: BigNumberish;
    },
    overrides?: CallOverrides
  ): Promise<boolean>;

  manager(overrides?: CallOverrides): Promise<string>;

  quote(
    path: BytesLike,
    amountDesired: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      amountIn: BigNumber;
      amountOut: BigNumber;
      gasUsed: BigNumber;
    }
  >;

  quoteSingle(
    tokenIn: string,
    tokenOut: string,
    tierChoices: BigNumberish,
    amountDesired: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      amountIn: BigNumber;
      amountOut: BigNumber;
      gasUsed: BigNumber;
    }
  >;

  simulate(
    path: BytesLike,
    amountDesired: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        protocolFeeAmt: BigNumber;
        tierAmountsIn: BigNumber[];
        tierData: BigNumber[];
      })[]
    ] & {
      amountIn: BigNumber;
      amountOut: BigNumber;
      hops: ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        protocolFeeAmt: BigNumber;
        tierAmountsIn: BigNumber[];
        tierData: BigNumber[];
      })[];
    }
  >;

  simulateSingle(
    tokenIn: string,
    tokenOut: string,
    tierChoices: BigNumberish,
    amountDesired: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
      amountIn: BigNumber;
      amountOut: BigNumber;
      protocolFeeAmt: BigNumber;
      tierAmountsIn: BigNumber[];
      tierData: BigNumber[];
    }
  >;

  callStatic: {
    getDerivedPosition(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, number, number, number] & {
          owner: string;
          token0: string;
          token1: string;
          tierId: number;
          tickLower: number;
          tickUpper: number;
        },
        [BigNumber, BigNumber, BigNumber, number, number] & {
          liquidityD8: BigNumber;
          feeGrowthInside0Last: BigNumber;
          feeGrowthInside1Last: BigNumber;
          limitOrderType: number;
          settlementSnapshotId: number;
        },
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        info: [string, string, string, number, number, number] & {
          owner: string;
          token0: string;
          token1: string;
          tierId: number;
          tickLower: number;
          tickUpper: number;
        };
        position: [BigNumber, BigNumber, BigNumber, number, number] & {
          liquidityD8: BigNumber;
          feeGrowthInside0Last: BigNumber;
          feeGrowthInside1Last: BigNumber;
          limitOrderType: number;
          settlementSnapshotId: number;
        };
        settled: boolean;
        amount0: BigNumber;
        amount1: BigNumber;
        feeAmount0: BigNumber;
        feeAmount1: BigNumber;
      }
    >;

    getFeeAmounts(
      tokenId: BigNumberish,
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { feeAmount0: BigNumber; feeAmount1: BigNumber }
    >;

    getPoolId(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getPosition(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string, number, number, number] & {
          owner: string;
          token0: string;
          token1: string;
          tierId: number;
          tickLower: number;
          tickUpper: number;
        },
        [BigNumber, BigNumber, BigNumber, number, number] & {
          liquidityD8: BigNumber;
          feeGrowthInside0Last: BigNumber;
          feeGrowthInside1Last: BigNumber;
          limitOrderType: number;
          settlementSnapshotId: number;
        }
      ] & {
        info: [string, string, string, number, number, number] & {
          owner: string;
          token0: string;
          token1: string;
          tierId: number;
          tickLower: number;
          tickUpper: number;
        };
        position: [BigNumber, BigNumber, BigNumber, number, number] & {
          liquidityD8: BigNumber;
          feeGrowthInside0Last: BigNumber;
          feeGrowthInside1Last: BigNumber;
          limitOrderType: number;
          settlementSnapshotId: number;
        };
      }
    >;

    getUnderlyingAmounts(
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      settled: boolean,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amount0: BigNumber; amount1: BigNumber }
    >;

    hub(overrides?: CallOverrides): Promise<string>;

    isSettled(
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<boolean>;

    manager(overrides?: CallOverrides): Promise<string>;

    quote(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        gasUsed: BigNumber;
      }
    >;

    quoteSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        gasUsed: BigNumber;
      }
    >;

    simulate(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        })[]
      ] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        hops: ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        })[];
      }
    >;

    simulateSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        protocolFeeAmt: BigNumber;
        tierAmountsIn: BigNumber[];
        tierData: BigNumber[];
      }
    >;
  };

  filters: {};

  estimateGas: {
    getDerivedPosition(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeeAmounts(
      tokenId: BigNumberish,
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPoolId(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPosition(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnderlyingAmounts(
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      settled: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hub(overrides?: CallOverrides): Promise<BigNumber>;

    isSettled(
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    quote(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    quoteSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    simulate(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    simulateSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getDerivedPosition(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeeAmounts(
      tokenId: BigNumberish,
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPoolId(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPosition(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUnderlyingAmounts(
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      settled: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hub(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isSettled(
      info: {
        owner: string;
        token0: string;
        token1: string;
        tierId: BigNumberish;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
      },
      position: {
        liquidityD8: BigNumberish;
        feeGrowthInside0Last: BigNumberish;
        feeGrowthInside1Last: BigNumberish;
        limitOrderType: BigNumberish;
        settlementSnapshotId: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quote(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    quoteSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    simulate(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    simulateSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
