/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IQuoterInterface extends ethers.utils.Interface {
  functions: {
    "hub()": FunctionFragment;
    "quote(bytes,int256)": FunctionFragment;
    "quoteSingle(address,address,uint256,int256)": FunctionFragment;
    "simulate(bytes,int256)": FunctionFragment;
    "simulateSingle(address,address,uint256,int256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "hub", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quote",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteSingle",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "simulate",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "simulateSingle",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "hub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "simulate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "simulateSingle",
    data: BytesLike
  ): Result;

  events: {};
}

export class IQuoter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IQuoterInterface;

  functions: {
    hub(overrides?: CallOverrides): Promise<[string]>;

    quote(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        gasUsed: BigNumber;
      }
    >;

    quoteSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        gasUsed: BigNumber;
      }
    >;

    simulate(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        })[]
      ] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        hops: ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        })[];
      }
    >;

    simulateSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        }
      ] & {
        hop: [BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        };
      }
    >;
  };

  hub(overrides?: CallOverrides): Promise<string>;

  quote(
    path: BytesLike,
    amountDesired: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      amountIn: BigNumber;
      amountOut: BigNumber;
      gasUsed: BigNumber;
    }
  >;

  quoteSingle(
    tokenIn: string,
    tokenOut: string,
    tierChoices: BigNumberish,
    amountDesired: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      amountIn: BigNumber;
      amountOut: BigNumber;
      gasUsed: BigNumber;
    }
  >;

  simulate(
    path: BytesLike,
    amountDesired: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        protocolFeeAmt: BigNumber;
        tierAmountsIn: BigNumber[];
        tierData: BigNumber[];
      })[]
    ] & {
      amountIn: BigNumber;
      amountOut: BigNumber;
      hops: ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        protocolFeeAmt: BigNumber;
        tierAmountsIn: BigNumber[];
        tierData: BigNumber[];
      })[];
    }
  >;

  simulateSingle(
    tokenIn: string,
    tokenOut: string,
    tierChoices: BigNumberish,
    amountDesired: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
      amountIn: BigNumber;
      amountOut: BigNumber;
      protocolFeeAmt: BigNumber;
      tierAmountsIn: BigNumber[];
      tierData: BigNumber[];
    }
  >;

  callStatic: {
    hub(overrides?: CallOverrides): Promise<string>;

    quote(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        gasUsed: BigNumber;
      }
    >;

    quoteSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        gasUsed: BigNumber;
      }
    >;

    simulate(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        })[]
      ] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        hops: ([BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
          amountIn: BigNumber;
          amountOut: BigNumber;
          protocolFeeAmt: BigNumber;
          tierAmountsIn: BigNumber[];
          tierData: BigNumber[];
        })[];
      }
    >;

    simulateSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber[], BigNumber[]] & {
        amountIn: BigNumber;
        amountOut: BigNumber;
        protocolFeeAmt: BigNumber;
        tierAmountsIn: BigNumber[];
        tierData: BigNumber[];
      }
    >;
  };

  filters: {};

  estimateGas: {
    hub(overrides?: CallOverrides): Promise<BigNumber>;

    quote(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    quoteSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    simulate(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    simulateSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    hub(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quote(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    quoteSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    simulate(
      path: BytesLike,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    simulateSingle(
      tokenIn: string,
      tokenOut: string,
      tierChoices: BigNumberish,
      amountDesired: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
